baseURL = 'https://eliel-monfort.github.io/EMcybertrack-Website/'
languageCode = 'en-us'
title = 'EM cybertrack site'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

menu:
  main:
    - identifier: Projects
      name: Projects
      url: /Projects/
      weight: 10
    - identifier: Blogs
      name: Blogs
      url: /Blogs/
      weight: 20