baseURL = 'https://eliel-monfort.github.io/EMcybertrack-Website/'
languageCode = 'en-us'
title = 'EM cybertrack site'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Products'
    pageRef = '/products'
    weight = 20
  [[menus.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 30
